# github actions
name: Publish to ghcr

on:
  push:
    branches:
      - main
      - feat/**
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

env:
  IMAGE_NAME: "ghcr.io/${{ github.repository }}"
jobs:
  "build":
    name: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}

      - uses: actions/checkout@v4.1.0

      - name: "Add sha to environment variable"
        env:
          FULL_SHA: "${{github.sha}}"
          REF: "${{github.ref}}"
        run: |
          sha=$(echo $FULL_SHA | cut -c1-7)
          branch=$(echo $REF | cut -c12-)
          if [ $branch = main ]
          then
              echo "IMAGE=$IMAGE_NAME:$sha" >> $GITHUB_ENV
          else 
              echo "IMAGE=$IMAGE_NAME-$branch:$sha" >> $GITHUB_ENV
          fi
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
